# in order for this to build mergin-client - on a mac - we need to run below in the terminal first - see https://github.com/MerginMaps/mergin-py-client/issues/164

    # export SQLite3_ROOT=/opt/homebrew/Cellar/sqlite/3.40.1/

name: dff2
variables:
  PGHOST: localhost
  PGUSER: postgres
  PGPORT: 5432
  PGDATABASE: bcfishpass
  DATABASE_URL: postgresql://postgres@localhost:5432/bcfishpass
  MERGIN_USERNAME: newgraph_airvine

channels:
  - conda-forge
  - defaults
dependencies:
  - wget
  - zip
  - unzip
  - python==3.11.7
  #- sqlite
  - pip
  - pip:
      - mergin-client
      - bcdata


